[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]
aptPkgs = ["python3-pip"]

[phases.install]
cmds = [
    "which python3",
    "which pip3 || which pip",
    "pip3 install -r requirements.txt || pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "python3 main.py"