[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "python3 -m pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "python3 main.py"