[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "python3 -m venv venv",
    "source venv/bin/activate && pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "source venv/bin/activate && python main.py"